---
logging:
  file: /var/vcap/sys/log/uaa/cf-registrar.log

  level: info

message_bus_servers:

  - nats://10.10.103.215:4222


uri:
  - uaa.10.10.18.45.xip.io
host: 10.10.18.45
index: 0
port: 8080
tags:
  component: uaa
varz:
  file: /home/config/varz.yml
